### ISSUE TITLE
Chest already open

### ISSUE THREAD

**Issue by LJMnin** [abyssonym/sai2_rando#1]
I got the shovel in Boa-Boa but then the vanilla shovel chest was already open and I don't know if this is intended or not (I needed the shovel to get the aqua stone to get there first). No codes were used and balance patch on.

**Comment by abyssonym** [comment]
This is not necessarily a bug. Some chests might be open by default, because it is not possible to put generic items like money in those chests. If there are such chests remaining after all of the unique items have been allotted, then those chests will be empty.

**Comment by abyssonym** [comment]
Beginning in v3, these chests should now contain "???" coins.
