### ISSUE TITLE
Impossible to Complete Seed #1550861963

### ISSUE THREAD

**Issue by jet082** [abyssonym/sai2_rando#5]
As in your comment

`# todo: sala_puka_warp might be blocked by high water level? Except to reach aqua switch. investigate
`

This seed seems to be impossible because of a required sala_puka_warp with high water.

**Comment by jet082** [comment]
NEVERMIND SPELLS WORK

**Comment by jet082** [comment]
NEVERMIND YOU COULD FEATHER TO THE ENTRANCE JUST CLOSE THE ISSUE haha

(that's super clever, actually, I love that that's in logic)

**Comment by abyssonym** [comment]
Indeed. I forgot to remove that line after investigating.
