### ISSUE TITLE
Star Spell Chest is already open when you get there if you've collected lots of items

### ISSUE THREAD

**Issue by ianestrachan** [abyssonym/sai2_rando#7]
Randomizer Version: 2
Seed: 1565454364S2
Options: Fast Text Speed

Related to #1, I encountered a soft-lock caused by a chest that was already open.

If I am reading the spoiler log correctly, `starspell_fb659  : 0453 powersword` means the Power Sword is located at the Star Spell location. (It has to be; it would be impossible for a spell to be located on Fuwa-Fuwa)

However, when I got to that chest, it was already open, presumably as I already had the Star Spell. This caused a soft lock as without the Power Sword it is impossible to complete Fuwa-Fuwa.

Oddly, all of the other Spell chests contained their items properly, even though I had all of the spells before I got the Elven Flute.

**Comment by abyssonym** [comment]
I played through this seed and found the power sword in the starspell location, so I'm not sure what was causing this. I'll leave this issue open for now.

**Comment by ianestrachan** [comment]
First, thank you for looking into this after so long, I'm glad to see more work being done on this randomizer.

I was curious what might be going on here, so I re-generated the seed with V2 and checked the spoiler log, taking the fastest possible route and picking up only items in the spoiler log. (It was painful.) Indeed, the Power Sword was there, where it was supposed to be.

So I started clearing out the islands and checking the Power Sword chest to see if it emptied, and it did not. But along the way I noticed some bosses and minibosses were already defeated by the time I got to them; for instance I already had the Light Stone by the time I got to the first boss but when I arrived it was already dead and the chest dropped immediately. So I had a thought, and went to grab the chest on Fuwa-Fuwa where the Power Sword *normally* is located in vanilla, then went back to Hiya-Hiya.

Sure enough, the Power Sword chest was now open and empty.

However, that was in V2, so I generated the same seed in V3 and tried again. While several issues had been fixed (minibosses and bosses not spawning if I already had the item they would normally drop in vanilla, for instance), by the time I got to the chest that should have had the Power Sword, it was already open and empty, even though I hadn't opened the chest on Fuwa-Fuwa that holds it in vanilla. This time I had picked up extra items and skipped some not-technically-required ones on the list in the spoiler log, so that might be playing into it. I'll try it again when I can on a fresh file and see what happens.

**Comment by ianestrachan** [comment]
Okay, I did a minimalist run in V3, and opened the chest that normally contains the Power Sword prior to going to the chest that it had been shuffled into, and the Power Sword was still there.

So I started grabbing more items and checking back periodically again. This time the tipping point was going to where the Power Fan normally is, and defeating the miniboss there and taking his item (a ??? coin bag); after doing this, the Power Sword chest was open and empty. 

But when I loaded an earlier save, went to that miniboss, beat him, took his items and went to the Power Sword, it was still there. I even opened the normal Power Sword chest (currently containing a magic bottle) and it remained.

So there is something about the process of picking up extra items (heart/magic bottles and coins, mostly) that seems to set up the game to eventually, when some chest is opened, accidentally mark the Power Sword as being picked up, too. Maybe it's some total number of items (I know there's that P counter on the filename that keeps increasing). So many different things seem to be causing it, I can't get solid reproduction steps.

**Comment by abyssonym** [comment]
This is very weird. Thanks for your work, I'll try to play through this in the BSNES debugger to figure out what's going on sometime soon.

**Comment by ianestrachan** [comment]
I started playing a different seed (1620184851S3, with fast text, no random encounters, quick magic switch, and quick shovel) and sort-of ran into a similar issue where by the time I got to the Star Spell chest, it was already open. 

Due to the seed's route I ended up cleaning out the entirety of Poka-Poka and almost all of Sala-Sala (except the chest behind the up-jab blocks) without visiting any other islands. Then I took the Sala->Hiya shortcut, used the Elven Flute, and went to the Star Spell area, only to find the chest was empty. I had not found any other empty chests in this run (but several ??? coin chests).

I checked the spoiler log at this point and it does not seem like anything important was in that location this time. But given that it was the exact same chest, there seems to be some interaction between collecting several items, and _that specific chest_.

**Comment by ianestrachan** [comment]
I had this happen in seed 1621036958 with that exact same chest once again, so it's something about the Star Spell chest specifically. I've updated the issue title accordingly.

**Comment by abyssonym** [comment]
Fixed in 88cf95678f6b787a40a0241fd556472f92b0ed51. There is a duplicate check for the star spell chest at **0x19b58**, for some reason. Hopefully fixing this didn't cause something else to break.

**Comment by ianestrachan** [comment]
Thank you very much for tracking this down (and #8 and #9 as well)!
